### ISSUE TITLE
WARNING: Issue connecting to battlelog. message

### ISSUE THREAD

**Issue by sec001** [AdKats/AdKats#827] opened 2015-10-30 09:03 UTC
![adkats](https://cloud.githubusercontent.com/assets/13351401/10844951/49ddfbd4-7f47-11e5-9feb-e6edbbc18afa.jpg)
Is using AdKats and AdKatsLRT; WARNING: Is there not any method that a message of Issue connecting to battlelog. is displayed, and a limit of LoadOut is against?

**Comment by ColColonCleaner** [comment] 2015-10-30 13:48
It's not closed till the issue is confirmed fixed. After making the changes we discussed on the forums please close this issue again if they do indeed fix it.

**Comment by sec001** [comment] 2015-10-30 13:54
I understood it.

If is recovered in 24 hours, is thankful; the message continues being still given, and the control of getting does not always go as we want a road.

**Comment by D3licat3** [comment] 2015-10-31 06:15
Hi!
We have almost the same problem since the BF Patch on tuesday. Not always but from time to time (when the server gets more populated) AdKatsLRT gives the "WARNING: Issue connecting to battlelog" message and LRT fails. Turning off and on again doesn't help.

**Comment by sec001** [comment] 2015-10-31 06:23
Hi!
MUU...   It may be the street certainly.
A movement check by the patch context couldn't be done, so I thought a setting mistake was done.

I turn off setting on a hacker check and am seeing how things are just in case.

**Comment by Super-Wong** [comment] 2015-10-31 06:43
I also get the same problem..
You can see. link is normal
But all Adkats and AdkatsRT are suggesting the link problem


And I found. If close Adkats alone
Just run separately AdkatsRT he will run normally

**Comment by Super-Wong** [comment] 2015-10-31 07:13
![4231](https://cloud.githubusercontent.com/assets/12322494/10862420/cf5cf932-7fe1-11e5-8e9c-c0123b3856ac.jpg)
And I found. If close Adkats alone
 Just run separately AdkatsRT he will run normally

**Comment by sec001** [comment] 2015-10-31 07:29
Using Procon two, and moving it.

It may be to reject that it is influence for use.

**Comment by sec001** [comment] 2015-10-31 12:48
![adkats_20151031](https://cloud.githubusercontent.com/assets/13351401/10863671/287d4616-8019-11e5-9b9d-0b5f7b252707.jpg)
Though 24 hours passed, and confirmed it; similar "WARNING: Issue connecting to battlelog" message is displayed.

The movement of the road out does not act in a timing same as a message being displayed

**Comment by sec001** [comment] 2015-11-02 22:49
It is felt after all if the immediate improvement that a Load out of AdKatsLRT did not act on normally even if I wait for 24 hours is necessary.

Because it is a very splendid function, I want to continue using it by all means.

**Comment by ColColonCleaner** [comment] 2015-11-12 03:06
If after turning off the LIVE system in AdKats and turning off high request volume in LRT this has not fixed your layer's issue connecting to battlelog, these plugins are not to blame. Something else is causing this issue for you, and I would suggest talking with your layer host about how many people are connecting from your layer's IP address. Cheers.

**Closed by ColColonCleaner** 2015-11-12 03:06 UTC

**Comment by sec001** [comment] 2015-11-12 03:16
Thank you very much for your ColColonCleaner and a series of correspondence, I thank.
LRT probes normal movement with doing, so this at present of ProconLayer, trout

**Comment by ColColonCleaner** [comment] 2015-11-12 03:17
I do not understand your last sentence. Are you still seeing this issue?

**Comment by sec001** [comment] 2015-11-12 03:23
The free probing which is being seen. I'm sorry not to be good at English so much.

**Comment by ColColonCleaner** [comment] 2015-11-12 03:37
Is it fixed? YES or NO.

**Comment by sec001** [comment] 2015-11-12 03:58
It's yes, it's a question, but is it better to change high request volume in LRT off?

**Comment by ColColonCleaner** [comment] 2015-11-12 04:00
Good to hear. No, if you can keep high request volume on without having issues you should keep it on. Turning it off gives your players a chance to cheat the system. Cheers.

**Comment by sec001** [comment] 2015-11-12 04:03
I see, thank you very much.
