### ISSUE TITLE
Adkats Extension: Loadout Enforcer not working correctly

### ISSUE THREAD

**Issue by Breakmaster90** [AdKats/AdKats#645] opened 2014-12-27 22:44 UTC
Hi,

i have your Adkats Extension the Loadout Enforcer.
There is a bug/glitch:
I limit Smoke, Airburst and C4, but:
Players already in server cant change to c4, while joining ppl can use airburst, c4, etc.

**Comment by epos85** [comment] 2015-01-01 02:29
So far so good, I will reply if I see any bugs later on.

Thanks for the fix, and have a happy new year!

Regards, 
Aleksander

**Comment by ColColonCleaner** [comment] 2015-01-04 05:55
Closing issue.

**Comment by ColColonCleaner** [comment] 2015-01-04 05:56
Marked invalid as this was not a bug with AdKats. For future inquiries please use the LRT repository.

**Closed by ColColonCleaner** 2015-01-04 05:55 UTC

**Comment by ColColonCleaner** [comment] 2015-03-22 18:48
https://github.com/isaacs/github/issues/253
