### ISSUE TITLE
DPS Automatic Ban false positive.

### ISSUE THREAD

**Issue by RowBan** [AdKats/AdKats#810] opened 2015-09-20 16:29 UTC
I just started playing BF4, and I was absolutely horrible at it. My brother (who's quite experienced and streams BF4 regularly. He's "MarcusVey" in most of my battlereports as I only ever play with him.) tells me he can log my account and play for a bit while I'm abroad and unlock some stuff for me. He does and while he's unlocking LMGs the server he's playing at crashes, he was using PKP-Pecheneg. He joins a different server and keeps playing. About a week later I get home, I want to play with him during his stream. I log into a server and after about 1 minute in deploy screen I get an "DPS Automatic Ban PKP-PECHENEG". Well that don't bother me much, we'll just play a different server then; and realization that a lot of servers seems to be using this automatic 3rd party ban program.

Afterwards we checked my pecheneg stats and the accuracy stats on my pkp-pecheneg on my battlelog was blank, despite having killed a lot of people with it. I log some random server that does not use 3rd party program to get an accuracy stat on my battlelog, after a map there's an accuracy stat and it's 8.7%.

Petitioned metabans but they say they are not involved in me getting banned and I have no active metaban on me. I gave up for a while, my brother asking me to play with him, I decide to give it a new shot since I can play almost no server because of this wrongful ban based on bugged stats. Google around a bit and found someone else being banned wrongfully with the same error message.

That's the story of how my BF4 account became useless about a week of playing :( Would love to get unbanned if at all possible. Otherwise I'll have to ask EA/Origin for a full refund since I can't really play BF4.

PS. We can't for the life of us find the battlereport either, the only battlereport where I've used the PKP Pecheneg is the one I played after the ban to get an accuracy stat on it.

http://battlelog.battlefield.com/bf4/soldier/L1pstick/stats/343251103/pc/
http://bf4db.com/players/16177315

**Comment by MarcusVey** [comment] 2015-09-20 17:00
Can confirm this (I was the one playing at the time).
Since I stream every time I'm online (twitch.tv/marcusvey) I can't really cheat out of the risk of getting both my twitch account and bf4 account terminated. (Cheating is against twitch's ToS as well).

My profile: http://battlelog.battlefield.com/bf4/soldier/MarcusVey/stats/339231520/pc/
BF4DB: http://bf4db.com/players/1020055

There isn't any "suspicious statistics" in any of our profiles, so I don't really understand what would've triggered the ban. As far as I understand from reading around a little, DPS Automatic Bans are triggered if you have a damage modifier or something like that running. Yet none of the stats report unusually high HKR....

**Comment by ColColonCleaner** [comment] 2015-09-20 17:02
This plugin is banning you based on overall statistics with your PKP. You can see your kill/hit statistics with that weapon here: http://bf4stats.com/pc/L1pstick

You have 62 kills with that weapon and 32 hits logged, which makes no sense, that would mean you killed nearly two people for every bullet landed on an enemy, which is even out of range for usual damage mods. It looks like that server crashing means it added kill stats but not hit stats for that round, which artificially makes it look like you have a damage mod.

I can logically see you are clean, but there is no way for the plugin to understand that, it thinks you are dealing 192 DPS with a 24 DPS weapon. I'll add some rejection cases for this, but that won't help you getting banned at this time. 

Any admin group that has banned you please show them this thread so they can whitelist you from actions through this plugin.

/hcwhitelist perm L1pstick

**Comment by MarcusVey** [comment] 2015-09-20 17:07
Ah, yeah I just found the same stats on 247fairplay: https://www.247fairplay.com/CheatDetector/L1pstick#toc-current-bf4-battlelog-stats

That's pretty rancid, considering the server crash also didn't generate a battle report for us to look at and now he's banned from multiple servers.

Which means we have to link this thread to every server with this plugin enabled on it, or only servers he's tried joining after the ban happened?

**Comment by ColColonCleaner** [comment] 2015-09-20 17:09
Bans with this plugin are not spread around (unless someone does that themselves), it's individual for each server. So if you join a server and are kicked with that ban message you were banned from that specific server and must appeal there. Just link this thread to those admins so they can understand quickly what is going on and can whitelist you.

**Comment by MarcusVey** [comment] 2015-09-20 17:16
Alright.

Thank you for the swift response and all the help!

**Comment by RowBan** [comment] 2015-09-20 17:25
That means only about 3 servers actually has me banned, that's very good! Thank you for the help, it is very much appreciated. Only really one server out of the ones I've been banned from I'm interested in getting back into anyway.

Also I had no idea how this plugin worked, just assumed that it was the bugged accuracy stat that got me banned. Not very good at analyzing data and stuff. I also find the battlelog to be quite confusing.

Thanks a bunch, ColColonCleaner.. lol

**Comment by ColColonCleaner** [comment] 2015-09-20 18:28
Closing. There is no reliable way to block this type of false positive from happening without hindering the ability to issue legitimate damage mod bans. This is a very situational problem caused by battlelog and should be handled on a case-by-case basis.

**Closed by ColColonCleaner** 2015-09-20 18:28 UTC

**Comment by wizard45** [comment] 2015-09-20 22:55
That's not your only issue. You have been stat padding as well which can cause you to be banned.

Longest Kill Steak: 102
 Longest Nemesis Steak:  44
