### ISSUE TITLE
adkats.sql

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#883] opened 2016-03-31 09:01 UTC
DROP TABLE IF EXISTS `adkats_usersoldiers`;
CREATE TABLE IF NOT EXISTS `adkats_usersoldiers` (
  `user_id` int(11) unsigned NOT NULL,
  `player_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`user_id`,`player_id`),
  KEY `adkats_usersoldiers_fk_user` (`user_id`),
  KEY `adkats_usersoldiers_fk_player` (`player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='AdKats - Connection of users to soldiers';

in this table the field "user_id" has many entries which are repeated for the same value (ex user_id 1 when he has many soldier) but doesn' this might create conflicts when used as primary key ?

**Comment by ChaT0n** [comment] 2016-03-31 12:51
And also another question about dps: wouldn't be more precise to calculate the dps with (kills-hs)/(hits-hs) than kills/hits ? cause the hs makes more damages than the usual damage on the body
Thanks

**Comment by ColColonCleaner** [comment] 2016-03-31 16:25
No, the primary key is a combination of user_id and player_id, that's how composite keys work. There can't be a duplicate of user 1 and player 1, but there can still be user 1 and player 2.

I do already handle the headshot case. I don't modify the DPS displayed because of headshots but i increase the trigger percentage based on the percentage of headshots, so the affect headshots have on whether a ban triggers is negated.

**Closed** 2016-04-02 20:38 UTC
Labels: Question
