### ISSUE TITLE
REQUEST For watchlist Feature 

### ISSUE THREAD

**Issue by EntraVenuS** [AdKats/AdKats#813] opened 2015-09-29 12:36 UTC
HI. I would like to request a feature. could there be a watchlist added to adkats with a simple command !watchlist Playername Reason, then the player would be added to a list that could be seen in adkats. 

Also could it be relayed back into game when a for example !watchlist current command is issued by admins, Then it could list the current names in the watchlist for admins to see. Probably keep the list to a maximum of 10 that can be deleted in adkats individually as and when the time is needed 

Thanks in advance Entra

**Comment by ColColonCleaner** [comment] 2015-09-29 16:09
Adding people to the lists is just a time consumption, but what do you want the list to do? Notifications on join? Leave? Auto-reports? Anything besides just a list of people?

**Comment by EntraVenuS** [comment] 2015-09-29 17:03
I guess a notification  on join if any admin is on the server then it will alert them to keep an eye on the guy in the list. A list of people with the recorded alleged offence / reason for being added to the watch list 
Regards Entra

**Comment by ColColonCleaner** [comment] 2015-11-12 03:56
Transitioning to unfunded request.

**Comment by ColColonCleaner** [comment] 2019-11-17 19:12
Duplicate of #1

**Closed by ColColonCleaner** 2019-11-17 19:12 UTC
Labels: Feature Request
