### ISSUE TITLE
ERROR: Unable to find target weight for command 8|72

### ISSUE THREAD

**Issue by sitekeeper** [AdKats/AdKats#754] opened 2015-04-14 03:25 UTC
Getting this today:
[21:31:11 01] [AdKats] ERROR: Unable to find target weight for command 8|72
[21:32:12 33] [AdKats] ERROR: Unable to find target weight for command 8|72

Any Ideas?
I seen the thread about [AdKats] ERROR: Unable to find source weight for command 7|73 and [AdKats] ERROR: Unable to find source weight for command 8|72

Not sure it it is related.
Thanks
Bob

**Comment by iraqiboy90** [comment] 2015-04-22 13:58
I've just encountered this today (source weight), out of many times for the past month/two.
It seems like the command ID has changed for "old perm-ban" & "old temp-ban"

Personally I've made the change on the records to contain the new appropriate ID, and it fixed the error spam.

**Comment by ColColonCleaner** [comment] 2015-04-23 00:44
Are you both using the web panel? That was a known bug there a while ago and the records could have been changed then. If they were not, for example they were changed using the /unban command, i'll look into it as an AdKats issue.

**Comment by iraqiboy90** [comment] 2015-04-23 00:52
Yes, I've been using webpanel since day 2-3 of using Adkats :)
I dont know but it may be the cause when changing a perm ban to temp ban through the webpanel. But i'm not sure. I've already done the record changes, so I dont remember which record it is anymore...

**Comment by sitekeeper** [comment] 2015-04-23 04:16
In my case it is from changing 2-3 month old Perm bans to temp bans and setting to expire in a set about of days. It does not seem to harm anything.

Thanks
Bob

**Comment by ColColonCleaner** [comment] 2015-04-23 04:19
The only thing this error will affect is player reputation.

Did you make those changes with the web panel?

**Comment by sitekeeper** [comment] 2015-04-23 04:20
Yes we did!

Thanks
Bob

**Comment by ColColonCleaner** [comment] 2015-04-23 04:21
@Prophet731 Can you confirm that this issue is fixed in the next web panel release?

**Comment by ColColonCleaner** [comment] 2015-08-16 23:11
I'll assume this is fixed by now.

**Closed by ColColonCleaner** 2015-08-16 23:11 UTC
