### ISSUE TITLE
REQUEST: Whitelist Admin for dont get kicked without Reserved Slot

### ISSUE THREAD

**Issue by III-Pho3niX-III** [AdKats/AdKats#923] opened 2016-07-13 13:20 UTC
Hi ColColonCleaner,

I want to ask for an request option example: (whitelist ping, balance etc.) for an Admin Whitelist. If an Admin does not have a reserved slot and that he is protected from being kicked by a VIP member.

Thanks in Advance!

**Comment by ColColonCleaner** [comment] 2016-07-16 01:32
So you don't want your admins to have reserved slots, but you want them to be protected from reserved slot kicks?

**Comment by III-Pho3niX-III** [comment] 2016-07-16 11:17
Some of our admins has reserved slot, but not all admins use a reserved slot. Thats correct, i want them protect for being reserved slot kicks!

**Comment by ColColonCleaner** [comment] 2016-07-30 22:57
Please send 5-10 bucks and i'll add this as an option. We would need to temporarily assign admins verbose reserved slots when they are in-server, just like we do for teamspeak whitelisting from VIP kicks.

**Comment by III-Pho3niX-III** [comment] 2016-07-31 00:34
done! I transferred some bucks with the same request name in the comment field.

**Comment by III-Pho3niX-III** [comment] 2016-07-31 09:19
Hi Colon,

Where to find the option to put admin on the whitelist from VIP kicks

**Comment by ColColonCleaner** [comment] 2016-07-31 14:28
There is no option yet, when this is closed it will be available.

**Comment by III-Pho3niX-III** [comment] 2016-07-31 15:04
Aaah ok, it is build-in and set as default now for all Admins! Thats great :)

**Comment by ColColonCleaner** [comment] 2016-07-31 15:06
no, it has not been added yet, i have yet to build it. i will close this ticket when i build it.

**Comment by ColColonCleaner** [comment] 2016-07-31 22:26
Ok update then look in section A16, you should see a setting for admin VIP kick whitelist. This is the setting you wanted. Please let me know if it works as intended.

**Comment by III-Pho3niX-III** [comment] 2016-07-31 22:44
Thanks! I will check it now and let you know tomorrow if it works yes or no

**Comment by III-Pho3niX-III** [comment] 2016-08-01 19:14
Hi Colon,

Let me test this few days ok. So you dont have to close this feature request.

**Comment by ColColonCleaner** [comment] 2016-08-01 19:16
No problem, let me know when you've been able to test. Thanks.

**Comment by III-Pho3niX-III** [comment] 2016-08-05 15:12
I think it's working Colon. I must see it on a long term. Keep this post open if you want.
Thanks for the good work!

**Comment by ColColonCleaner** [comment] 2016-08-05 15:15
I'm going to close it for now. Please reopen it if you see issues. Cheers.

**Closed by ColColonCleaner** 2016-08-05 15:15 UTC
Labels: Feature Request, Funded, PATCH COMPLETE

**Comment by III-Pho3niX-III** [comment] 2016-08-24 23:49
Something get wrong when Automatic VIP Kick Whitelist for Admins is enabled. It automatically inserts a reserved slot to the list, and this is not the intention. Can you take a look at?

Thanks for the good job!

**Comment by ColColonCleaner** [comment] 2016-08-24 23:50
That is how the system works. While they are in the server it adds them to the reserved slot list so the server doesn't kick them for other VIPs. When they leave the server, the slot is removed.

**Comment by III-Pho3niX-III** [comment] 2016-08-25 05:52
Ok, i undestand now! Didn't know that :)
Thank you.
